# NumPy Basics

This notebook contains my NumPy practice.

In [1]:
import numpy as np

## Creating a Numpy Array

In [14]:
A = np.array([1, 2, 3])
print(A)
 
B = np.array([[1, 2, 3], [4, 5, 6]])
print(B)
 
C = np.array((1, 3, 2))
print(C)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[1 3 2]


## Accessing the Array Index

In [15]:
A = np.array([[-1, 2, 0, 4],[4, -0.5, 6, 0],[2.6, 0, 7, 8],[3, -7, 4, 2.0]])

B = A[:2, ::2]
print("B:",B)

C = A[[1, 1, 0, 3], [3, 2, 1, 0]]
print("C:",C)

B: [[-1.  0.]
 [ 4.  6.]]
C: [0. 6. 2. 3.]


## Basic Array Operations

In [16]:
a = np.array([[1, 2],[3, 4]])

b = np.array([[4, 3],[2, 1]])

print("a+1: ", a + 1)
print("b-2: ", b - 2)
print("Sum of all elements in a: ", a.sum())
print("a+b: ", a + b)

a+1:  [[2 3]
 [4 5]]
b-2:  [[ 2  1]
 [ 0 -1]]
Sum of all elements in a:  10
a+b:  [[5 5]
 [5 5]]


## Data Types in Numpy

In [17]:
x = np.array([1, 2])  
print(x.dtype)         
 
x = np.array([1.0, 2.0]) 
print(x.dtype)  
 
x = np.array([1, 2], dtype = np.int64)   
print(x.dtype)

int64
float64
int64


## Math Operations on DataType Array

In [18]:
A = np.array([[4, 7], [2, 6]], dtype=np.float64)
B = np.array([[3, 6], [2, 8]], dtype=np.float64)

print(np.add(A, B))
print(np.sum(A))
print(np.sqrt(A))
print(A.T)

[[ 7. 13.]
 [ 4. 14.]]
19.0
[[2.         2.64575131]
 [1.41421356 2.44948974]]
[[4. 2.]
 [7. 6.]]


## Array Shapes and Dimensions

In [19]:
A = np.array([1, 2, 3])

B = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

C = np.array([
    [1],
    [2],
    [3]
])

print("A shape:", A.shape)
print("A dimensions:", A.ndim)

print("B shape:", B.shape)
print("B dimensions:", B.ndim)

print("C shape:", C.shape)
print("C dimensions:", C.ndim)

A shape: (3,)
A dimensions: 1
B shape: (2, 3)
B dimensions: 2
C shape: (3, 1)
C dimensions: 2


## Reshaping Arrays

In [21]:
A = np.array([1, 2, 3, 4, 5, 6])

print(A.shape)

B = A.reshape(2, 3)
print(B)
print(B.shape)

C = A.reshape(3, 2)
print(C)
print(C.shape)

D = A.reshape(6, 1)
print(D)
print(D.shape)

(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


## Matrix Multiplication

In [22]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print("Element-wise multiplication:")
print(A * B)

print("Matrix multiplication:")
print(A @ B)

Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]


In [23]:
A = np.random.randn(3, 2)
B = np.random.randn(2, 4)

print("A:", A.shape)
print("B:", B.shape)

C = A @ B

print("C:", C.shape)

A: (3, 2)
B: (2, 4)
C: (3, 4)


In [24]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

print(A * B)
print(A / B)
print(A ** 2)

[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[ 1  4]
 [ 9 16]]


## Sum and Mean Along Axes

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("Total:", np.sum(A))

print("axis=0:", np.sum(A, axis=0))
print("axis=1:", np.sum(A, axis=1))

print("Mean:", np.mean(A))

Total: 21
axis=0: [5 7 9]
axis=1: [ 6 15]
Mean: 3.5


## Broadcasting

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

b = np.array([
    [10],
    [20]
])

print("A shape:", A.shape)
print("b shape:", b.shape)

print(A + b)

A shape: (2, 3)
b shape: (2, 1)
[[11 12 13]
 [24 25 26]]


## Random Numbers and Initialization

In [29]:
A = np.random.randn(3, 2)

print(A)
print(A.shape)

[[ 1.57921282  0.76743473]
 [-0.46947439  0.54256004]
 [-0.46341769 -0.46572975]]
(3, 2)


In [30]:
np.random.seed(42)

A = np.random.randn(3, 2)

print(A)

[[ 0.49671415 -0.1382643 ]
 [ 0.64768854  1.52302986]
 [-0.23415337 -0.23413696]]
